/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProcurementIndexRouteImport } from './routes/procurement.index'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProcurementSlugRouteImport } from './routes/procurement.$slug'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as AdminSiteContentRouteImport } from './routes/admin.site-content'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProcurementsRouteImport } from './routes/admin.procurements'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProcurementsIndexRouteImport } from './routes/admin.procurements.index'
import { Route as AdminCareersIndexRouteImport } from './routes/admin.careers.index'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsSlugRouteImport } from './routes/admin.products.$slug'
import { Route as AdminProcurementsNewRouteImport } from './routes/admin.procurements.new'
import { Route as AdminProcurementsSlugRouteImport } from './routes/admin.procurements.$slug'
import { Route as AdminCareersNewRouteImport } from './routes/admin.careers.new'
import { Route as AdminCareersSlugRouteImport } from './routes/admin.careers.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementIndexRoute = ProcurementIndexRouteImport.update({
  id: '/procurement/',
  path: '/procurement/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementSlugRoute = ProcurementSlugRouteImport.update({
  id: '/procurement/$slug',
  path: '/procurement/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSiteContentRoute = AdminSiteContentRouteImport.update({
  id: '/site-content',
  path: '/site-content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcurementsRoute = AdminProcurementsRouteImport.update({
  id: '/procurements',
  path: '/procurements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProcurementsIndexRoute = AdminProcurementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProcurementsRoute,
} as any)
const AdminCareersIndexRoute = AdminCareersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCareersRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsSlugRoute = AdminProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProcurementsNewRoute = AdminProcurementsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProcurementsRoute,
} as any)
const AdminProcurementsSlugRoute = AdminProcurementsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminProcurementsRoute,
} as any)
const AdminCareersNewRoute = AdminCareersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCareersRoute,
} as any)
const AdminCareersSlugRoute = AdminCareersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminCareersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/careers': typeof AdminCareersRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/procurements': typeof AdminProcurementsRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/site-content': typeof AdminSiteContentRoute
  '/api/upload': typeof ApiUploadRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/procurement/$slug': typeof ProcurementSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/procurement/': typeof ProcurementIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/careers/$slug': typeof AdminCareersSlugRoute
  '/admin/careers/new': typeof AdminCareersNewRoute
  '/admin/procurements/$slug': typeof AdminProcurementsSlugRoute
  '/admin/procurements/new': typeof AdminProcurementsNewRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/careers/': typeof AdminCareersIndexRoute
  '/admin/procurements/': typeof AdminProcurementsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/api/upload': typeof ApiUploadRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/procurement/$slug': typeof ProcurementSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/careers': typeof CareersIndexRoute
  '/procurement': typeof ProcurementIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/careers/$slug': typeof AdminCareersSlugRoute
  '/admin/careers/new': typeof AdminCareersNewRoute
  '/admin/procurements/$slug': typeof AdminProcurementsSlugRoute
  '/admin/procurements/new': typeof AdminProcurementsNewRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/careers': typeof AdminCareersIndexRoute
  '/admin/procurements': typeof AdminProcurementsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/careers': typeof AdminCareersRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/procurements': typeof AdminProcurementsRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/site-content': typeof AdminSiteContentRoute
  '/api/upload': typeof ApiUploadRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/procurement/$slug': typeof ProcurementSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/procurement/': typeof ProcurementIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/careers/$slug': typeof AdminCareersSlugRoute
  '/admin/careers/new': typeof AdminCareersNewRoute
  '/admin/procurements/$slug': typeof AdminProcurementsSlugRoute
  '/admin/procurements/new': typeof AdminProcurementsNewRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/careers/': typeof AdminCareersIndexRoute
  '/admin/procurements/': typeof AdminProcurementsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/admin/careers'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/procurements'
    | '/admin/products'
    | '/admin/site-content'
    | '/api/upload'
    | '/careers/$slug'
    | '/procurement/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/careers/'
    | '/procurement/'
    | '/products/'
    | '/admin/careers/$slug'
    | '/admin/careers/new'
    | '/admin/procurements/$slug'
    | '/admin/procurements/new'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/careers/'
    | '/admin/procurements/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/site-content'
    | '/api/upload'
    | '/careers/$slug'
    | '/procurement/$slug'
    | '/products/$slug'
    | '/admin'
    | '/careers'
    | '/procurement'
    | '/products'
    | '/admin/careers/$slug'
    | '/admin/careers/new'
    | '/admin/procurements/$slug'
    | '/admin/procurements/new'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/careers'
    | '/admin/procurements'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/admin/careers'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/procurements'
    | '/admin/products'
    | '/admin/site-content'
    | '/api/upload'
    | '/careers/$slug'
    | '/procurement/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/careers/'
    | '/procurement/'
    | '/products/'
    | '/admin/careers/$slug'
    | '/admin/careers/new'
    | '/admin/procurements/$slug'
    | '/admin/procurements/new'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/careers/'
    | '/admin/procurements/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiUploadRoute: typeof ApiUploadRoute
  CareersSlugRoute: typeof CareersSlugRoute
  ProcurementSlugRoute: typeof ProcurementSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CareersIndexRoute: typeof CareersIndexRoute
  ProcurementIndexRoute: typeof ProcurementIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/': {
      id: '/procurement/'
      path: '/procurement'
      fullPath: '/procurement/'
      preLoaderRoute: typeof ProcurementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/$slug': {
      id: '/procurement/$slug'
      path: '/procurement/$slug'
      fullPath: '/procurement/$slug'
      preLoaderRoute: typeof ProcurementSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/site-content': {
      id: '/admin/site-content'
      path: '/site-content'
      fullPath: '/admin/site-content'
      preLoaderRoute: typeof AdminSiteContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/procurements': {
      id: '/admin/procurements'
      path: '/procurements'
      fullPath: '/admin/procurements'
      preLoaderRoute: typeof AdminProcurementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/procurements/': {
      id: '/admin/procurements/'
      path: '/'
      fullPath: '/admin/procurements/'
      preLoaderRoute: typeof AdminProcurementsIndexRouteImport
      parentRoute: typeof AdminProcurementsRoute
    }
    '/admin/careers/': {
      id: '/admin/careers/'
      path: '/'
      fullPath: '/admin/careers/'
      preLoaderRoute: typeof AdminCareersIndexRouteImport
      parentRoute: typeof AdminCareersRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$slug': {
      id: '/admin/products/$slug'
      path: '/$slug'
      fullPath: '/admin/products/$slug'
      preLoaderRoute: typeof AdminProductsSlugRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/procurements/new': {
      id: '/admin/procurements/new'
      path: '/new'
      fullPath: '/admin/procurements/new'
      preLoaderRoute: typeof AdminProcurementsNewRouteImport
      parentRoute: typeof AdminProcurementsRoute
    }
    '/admin/procurements/$slug': {
      id: '/admin/procurements/$slug'
      path: '/$slug'
      fullPath: '/admin/procurements/$slug'
      preLoaderRoute: typeof AdminProcurementsSlugRouteImport
      parentRoute: typeof AdminProcurementsRoute
    }
    '/admin/careers/new': {
      id: '/admin/careers/new'
      path: '/new'
      fullPath: '/admin/careers/new'
      preLoaderRoute: typeof AdminCareersNewRouteImport
      parentRoute: typeof AdminCareersRoute
    }
    '/admin/careers/$slug': {
      id: '/admin/careers/$slug'
      path: '/$slug'
      fullPath: '/admin/careers/$slug'
      preLoaderRoute: typeof AdminCareersSlugRouteImport
      parentRoute: typeof AdminCareersRoute
    }
  }
}

interface AdminCareersRouteChildren {
  AdminCareersSlugRoute: typeof AdminCareersSlugRoute
  AdminCareersNewRoute: typeof AdminCareersNewRoute
  AdminCareersIndexRoute: typeof AdminCareersIndexRoute
}

const AdminCareersRouteChildren: AdminCareersRouteChildren = {
  AdminCareersSlugRoute: AdminCareersSlugRoute,
  AdminCareersNewRoute: AdminCareersNewRoute,
  AdminCareersIndexRoute: AdminCareersIndexRoute,
}

const AdminCareersRouteWithChildren = AdminCareersRoute._addFileChildren(
  AdminCareersRouteChildren,
)

interface AdminProcurementsRouteChildren {
  AdminProcurementsSlugRoute: typeof AdminProcurementsSlugRoute
  AdminProcurementsNewRoute: typeof AdminProcurementsNewRoute
  AdminProcurementsIndexRoute: typeof AdminProcurementsIndexRoute
}

const AdminProcurementsRouteChildren: AdminProcurementsRouteChildren = {
  AdminProcurementsSlugRoute: AdminProcurementsSlugRoute,
  AdminProcurementsNewRoute: AdminProcurementsNewRoute,
  AdminProcurementsIndexRoute: AdminProcurementsIndexRoute,
}

const AdminProcurementsRouteWithChildren =
  AdminProcurementsRoute._addFileChildren(AdminProcurementsRouteChildren)

interface AdminProductsRouteChildren {
  AdminProductsSlugRoute: typeof AdminProductsSlugRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsSlugRoute: AdminProductsSlugRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminCareersRoute: typeof AdminCareersRouteWithChildren
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProcurementsRoute: typeof AdminProcurementsRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminSiteContentRoute: typeof AdminSiteContentRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCareersRoute: AdminCareersRouteWithChildren,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProcurementsRoute: AdminProcurementsRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminSiteContentRoute: AdminSiteContentRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiUploadRoute: ApiUploadRoute,
  CareersSlugRoute: CareersSlugRoute,
  ProcurementSlugRoute: ProcurementSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CareersIndexRoute: CareersIndexRoute,
  ProcurementIndexRoute: ProcurementIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
